from __future__ import annotations

from typing import Any


SUPPLEMENTAL_MEDICATIONS: list[dict[str, Any]] = [
    {"name": "Acetaminophen", "class": "analgesic", "high_daily_mg": 3000, "max_daily_mg": 4000},
    {"name": "Acyclovir", "class": "antiviral", "high_daily_mg": 3200, "max_daily_mg": 4000},
    {"name": "Adalimumab", "class": "biologic_dmard", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Albuterol", "class": "short_acting_beta_agonist", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Alendronate", "class": "bisphosphonate", "high_daily_mg": 70, "max_daily_mg": 70},
    {"name": "Alirocumab", "class": "pcsk9_inhibitor", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Allopurinol", "class": "xanthine_oxidase_inhibitor", "high_daily_mg": 600, "max_daily_mg": 800},
    {"name": "Alprazolam", "class": "benzodiazepine", "high_daily_mg": 4, "max_daily_mg": 10},
    {"name": "Amiodarone", "class": "antiarrhythmic", "high_daily_mg": 400, "max_daily_mg": 800},
    {"name": "Amitriptyline", "class": "tricyclic_antidepressant", "high_daily_mg": 100, "max_daily_mg": 300},
    {"name": "Amoxicillin", "class": "penicillin_antibiotic", "high_daily_mg": 3000, "max_daily_mg": 4000},
    {"name": "Amoxicillin Clavulanate", "class": "penicillin_antibiotic", "high_daily_mg": 3000, "max_daily_mg": 4000},
    {"name": "Ampicillin", "class": "penicillin_antibiotic", "high_daily_mg": 8000, "max_daily_mg": 12000},
    {"name": "Anastrozole", "class": "aromatase_inhibitor", "high_daily_mg": 1, "max_daily_mg": 1},
    {"name": "Apixaban", "class": "direct_oral_anticoagulant", "high_daily_mg": 10, "max_daily_mg": 20},
    {"name": "Aripiprazole", "class": "atypical_antipsychotic", "high_daily_mg": 15, "max_daily_mg": 30},
    {"name": "Azathioprine", "class": "immunosuppressant", "high_daily_mg": 150, "max_daily_mg": 300},
    {"name": "Azithromycin", "class": "macrolide_antibiotic", "high_daily_mg": 500, "max_daily_mg": 2000},
    {"name": "Baclofen", "class": "muscle_relaxant", "high_daily_mg": 60, "max_daily_mg": 80},
    {"name": "Beclomethasone", "class": "inhaled_corticosteroid", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Benzoyl Peroxide", "class": "topical_acne_agent", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Benazepril", "class": "ace_inhibitor", "high_daily_mg": 40, "max_daily_mg": 80},
    {"name": "Bevacizumab", "class": "monoclonal_antibody_oncology", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Bicalutamide", "class": "antiandrogen", "high_daily_mg": 50, "max_daily_mg": 150},
    {"name": "Bisacodyl", "class": "stimulant_laxative", "high_daily_mg": 10, "max_daily_mg": 30},
    {"name": "Bisoprolol", "class": "beta_blocker", "high_daily_mg": 10, "max_daily_mg": 20},
    {"name": "Brimonidine", "class": "ophthalmic_alpha_agonist", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Budesonide", "class": "corticosteroid", "high_daily_mg": 9, "max_daily_mg": 18},
    {"name": "Budesonide Inhaler", "class": "inhaled_corticosteroid", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Bumetanide", "class": "loop_diuretic", "high_daily_mg": 6, "max_daily_mg": 10},
    {"name": "Bupropion", "class": "antidepressant", "high_daily_mg": 300, "max_daily_mg": 450},
    {"name": "Buspirone", "class": "anxiolytic", "high_daily_mg": 45, "max_daily_mg": 60},
    {"name": "Calcitonin", "class": "bone_metabolism_agent", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Calcium Carbonate", "class": "mineral_supplement", "high_daily_mg": 2000, "max_daily_mg": 2500},
    {"name": "Canagliflozin", "class": "sglt2_inhibitor", "high_daily_mg": 300, "max_daily_mg": 300},
    {"name": "Candesartan", "class": "angiotensin_receptor_blocker", "high_daily_mg": 32, "max_daily_mg": 32},
    {"name": "Capecitabine", "class": "oncology_antimetabolite", "high_daily_mg": 2500, "max_daily_mg": 5000},
    {"name": "Carbamazepine", "class": "antiepileptic", "high_daily_mg": 1200, "max_daily_mg": 1600},
    {"name": "Carbidopa Levodopa", "class": "parkinson_agent", "high_daily_mg": 800, "max_daily_mg": 1200},
    {"name": "Carboplatin", "class": "platinum_chemotherapy", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Carvedilol", "class": "beta_blocker", "high_daily_mg": 50, "max_daily_mg": 100},
    {"name": "Cefdinir", "class": "cephalosporin_antibiotic", "high_daily_mg": 600, "max_daily_mg": 600},
    {"name": "Cefixime", "class": "cephalosporin_antibiotic", "high_daily_mg": 400, "max_daily_mg": 400},
    {"name": "Ceftriaxone", "class": "cephalosporin_antibiotic", "high_daily_mg": 2000, "max_daily_mg": 4000},
    {"name": "Cefuroxime", "class": "cephalosporin_antibiotic", "high_daily_mg": 1000, "max_daily_mg": 1000},
    {"name": "Celecoxib", "class": "nsaid", "high_daily_mg": 400, "max_daily_mg": 400},
    {"name": "Cephalexin", "class": "cephalosporin_antibiotic", "high_daily_mg": 3000, "max_daily_mg": 4000},
    {"name": "Cetirizine", "class": "antihistamine", "high_daily_mg": 10, "max_daily_mg": 20},
    {"name": "Chlorthalidone", "class": "thiazide_diuretic", "high_daily_mg": 25, "max_daily_mg": 100},
    {"name": "Ciprofloxacin", "class": "fluoroquinolone_antibiotic", "high_daily_mg": 1000, "max_daily_mg": 1500},
    {"name": "Cisplatin", "class": "platinum_chemotherapy", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Citalopram", "class": "ssri", "high_daily_mg": 20, "max_daily_mg": 40},
    {"name": "Clarithromycin", "class": "macrolide_antibiotic", "high_daily_mg": 1000, "max_daily_mg": 1000},
    {"name": "Clindamycin", "class": "lincosamide_antibiotic", "high_daily_mg": 1800, "max_daily_mg": 2700},
    {"name": "Clobetasol", "class": "topical_corticosteroid", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Clomiphene", "class": "fertility_agent", "high_daily_mg": 100, "max_daily_mg": 100},
    {"name": "Clonazepam", "class": "benzodiazepine", "high_daily_mg": 4, "max_daily_mg": 20},
    {"name": "Codeine", "class": "opioid_analgesic", "high_daily_mg": 240, "max_daily_mg": 360},
    {"name": "Colchicine", "class": "anti_gout", "high_daily_mg": 1.2, "max_daily_mg": 2.4},
    {"name": "Cyclobenzaprine", "class": "muscle_relaxant", "high_daily_mg": 30, "max_daily_mg": 30},
    {"name": "Cyclophosphamide", "class": "alkylating_chemotherapy", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Cyclosporine", "class": "calcineurin_inhibitor", "high_daily_mg": 400, "max_daily_mg": 600},
    {"name": "Cyanocobalamin", "class": "vitamin", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Dabigatran", "class": "direct_oral_anticoagulant", "high_daily_mg": 300, "max_daily_mg": 300},
    {"name": "Dapagliflozin", "class": "sglt2_inhibitor", "high_daily_mg": 10, "max_daily_mg": 10},
    {"name": "Dasatinib", "class": "tyrosine_kinase_inhibitor", "high_daily_mg": 100, "max_daily_mg": 180},
    {"name": "Desloratadine", "class": "antihistamine", "high_daily_mg": 5, "max_daily_mg": 5},
    {"name": "Desvenlafaxine", "class": "snri", "high_daily_mg": 100, "max_daily_mg": 400},
    {"name": "Diazepam", "class": "benzodiazepine", "high_daily_mg": 20, "max_daily_mg": 40},
    {"name": "Diclofenac", "class": "nsaid", "high_daily_mg": 100, "max_daily_mg": 150},
    {"name": "Digoxin", "class": "cardiac_glycoside", "high_daily_mg": 0.25, "max_daily_mg": 0.5},
    {"name": "Diltiazem", "class": "calcium_channel_blocker", "high_daily_mg": 360, "max_daily_mg": 540},
    {"name": "Diphenhydramine", "class": "antihistamine", "high_daily_mg": 200, "max_daily_mg": 300},
    {"name": "Disulfiram", "class": "alcohol_use_disorder_agent", "high_daily_mg": 500, "max_daily_mg": 500},
    {"name": "Docusate", "class": "stool_softener", "high_daily_mg": 300, "max_daily_mg": 500},
    {"name": "Docetaxel", "class": "taxane_chemotherapy", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Domperidone", "class": "prokinetic", "high_daily_mg": 30, "max_daily_mg": 80},
    {"name": "Donepezil", "class": "cholinesterase_inhibitor", "high_daily_mg": 10, "max_daily_mg": 23},
    {"name": "Doxorubicin", "class": "anthracycline_chemotherapy", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Dronedarone", "class": "antiarrhythmic", "high_daily_mg": 800, "max_daily_mg": 800},
    {"name": "Dulaglutide", "class": "glp1_receptor_agonist", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Duloxetine", "class": "snri", "high_daily_mg": 60, "max_daily_mg": 120},
    {"name": "Dutasteride", "class": "5_alpha_reductase_inhibitor", "high_daily_mg": 0.5, "max_daily_mg": 0.5},
    {"name": "Edoxaban", "class": "direct_oral_anticoagulant", "high_daily_mg": 60, "max_daily_mg": 60},
    {"name": "Empagliflozin", "class": "sglt2_inhibitor", "high_daily_mg": 25, "max_daily_mg": 25},
    {"name": "Enalapril", "class": "ace_inhibitor", "high_daily_mg": 40, "max_daily_mg": 40},
    {"name": "Enoxaparin", "class": "low_molecular_weight_heparin", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Entecavir", "class": "antiviral", "high_daily_mg": 1, "max_daily_mg": 1},
    {"name": "Enzalutamide", "class": "antiandrogen", "high_daily_mg": 160, "max_daily_mg": 160},
    {"name": "Epinephrine", "class": "emergency_sympathomimetic", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Epoetin Alfa", "class": "erythropoiesis_stimulating_agent", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Erlotinib", "class": "tyrosine_kinase_inhibitor", "high_daily_mg": 150, "max_daily_mg": 150},
    {"name": "Erythromycin", "class": "macrolide_antibiotic", "high_daily_mg": 2000, "max_daily_mg": 4000},
    {"name": "Escitalopram", "class": "ssri", "high_daily_mg": 20, "max_daily_mg": 20},
    {"name": "Esomeprazole", "class": "ppi", "high_daily_mg": 40, "max_daily_mg": 80},
    {"name": "Etanercept", "class": "biologic_dmard", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Ethinyl Estradiol Levonorgestrel", "class": "combined_hormonal_contraceptive", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Etoposide", "class": "topoisomerase_inhibitor", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Evolocumab", "class": "pcsk9_inhibitor", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Everolimus", "class": "mtor_inhibitor", "high_daily_mg": 10, "max_daily_mg": 10},
    {"name": "Exemestane", "class": "aromatase_inhibitor", "high_daily_mg": 25, "max_daily_mg": 25},
    {"name": "Famotidine", "class": "h2_blocker", "high_daily_mg": 40, "max_daily_mg": 80},
    {"name": "Febuxostat", "class": "xanthine_oxidase_inhibitor", "high_daily_mg": 80, "max_daily_mg": 120},
    {"name": "Fenofibrate", "class": "fibrate", "high_daily_mg": 145, "max_daily_mg": 200},
    {"name": "Fentanyl", "class": "opioid_analgesic", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Ferrous Sulfate", "class": "iron_supplement", "high_daily_mg": 195, "max_daily_mg": 300},
    {"name": "Fexofenadine", "class": "antihistamine", "high_daily_mg": 180, "max_daily_mg": 180},
    {"name": "Filgrastim", "class": "colony_stimulating_factor", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Finasteride", "class": "5_alpha_reductase_inhibitor", "high_daily_mg": 5, "max_daily_mg": 5},
    {"name": "Flecainide", "class": "antiarrhythmic", "high_daily_mg": 300, "max_daily_mg": 400},
    {"name": "Fluconazole", "class": "azole_antifungal", "high_daily_mg": 400, "max_daily_mg": 800},
    {"name": "Fluticasone Inhaler", "class": "inhaled_corticosteroid", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Fluticasone Nasal", "class": "nasal_corticosteroid", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Folic Acid", "class": "vitamin", "high_daily_mg": 1, "max_daily_mg": 5},
    {"name": "Formoterol", "class": "long_acting_beta_agonist", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Fosfomycin", "class": "antibiotic", "high_daily_mg": 3000, "max_daily_mg": 3000},
    {"name": "Gabapentin", "class": "gabapentinoid", "high_daily_mg": 2400, "max_daily_mg": 3600},
    {"name": "Gefitinib", "class": "tyrosine_kinase_inhibitor", "high_daily_mg": 250, "max_daily_mg": 250},
    {"name": "Gemcitabine", "class": "oncology_antimetabolite", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Gemfibrozil", "class": "fibrate", "high_daily_mg": 1200, "max_daily_mg": 1200},
    {"name": "Gentamicin", "class": "aminoglycoside_antibiotic", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Gliclazide", "class": "sulfonylurea", "high_daily_mg": 120, "max_daily_mg": 320},
    {"name": "Glipizide", "class": "sulfonylurea", "high_daily_mg": 20, "max_daily_mg": 40},
    {"name": "Glyburide", "class": "sulfonylurea", "high_daily_mg": 10, "max_daily_mg": 20},
    {"name": "Haloperidol", "class": "typical_antipsychotic", "high_daily_mg": 10, "max_daily_mg": 30},
    {"name": "Heparin", "class": "anticoagulant", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Hydrochlorothiazide", "class": "thiazide_diuretic", "high_daily_mg": 25, "max_daily_mg": 100},
    {"name": "Hydrocodone", "class": "opioid_analgesic", "high_daily_mg": 40, "max_daily_mg": 90},
    {"name": "Hydrocortisone Topical", "class": "topical_corticosteroid", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Hydroxychloroquine", "class": "dmard", "high_daily_mg": 400, "max_daily_mg": 600},
    {"name": "Hydroxyurea", "class": "antimetabolite", "high_daily_mg": 2000, "max_daily_mg": 3000},
    {"name": "Hydroxyzine", "class": "antihistamine", "high_daily_mg": 100, "max_daily_mg": 400},
    {"name": "Ibandronate", "class": "bisphosphonate", "high_daily_mg": 150, "max_daily_mg": 150},
    {"name": "Imatinib", "class": "tyrosine_kinase_inhibitor", "high_daily_mg": 400, "max_daily_mg": 800},
    {"name": "Indapamide", "class": "thiazide_like_diuretic", "high_daily_mg": 2.5, "max_daily_mg": 5},
    {"name": "Indomethacin", "class": "nsaid", "high_daily_mg": 150, "max_daily_mg": 200},
    {"name": "Infliximab", "class": "biologic_dmard", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Insulin Aspart", "class": "insulin", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Insulin Degludec", "class": "insulin", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Insulin Detemir", "class": "insulin", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Insulin Lispro", "class": "insulin", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Ipratropium", "class": "anticholinergic_bronchodilator", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Irbesartan", "class": "angiotensin_receptor_blocker", "high_daily_mg": 300, "max_daily_mg": 300},
    {"name": "Iron Sucrose", "class": "iron_supplement", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Isosorbide Mononitrate", "class": "nitrate", "high_daily_mg": 120, "max_daily_mg": 240},
    {"name": "Isotretinoin", "class": "retinoid", "high_daily_mg": 80, "max_daily_mg": 160},
    {"name": "Itraconazole", "class": "azole_antifungal", "high_daily_mg": 400, "max_daily_mg": 600},
    {"name": "Ketorolac", "class": "nsaid", "high_daily_mg": 40, "max_daily_mg": 40},
    {"name": "Lactulose", "class": "osmotic_laxative", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Lamotrigine", "class": "antiepileptic", "high_daily_mg": 200, "max_daily_mg": 500},
    {"name": "Lansoprazole", "class": "ppi", "high_daily_mg": 30, "max_daily_mg": 60},
    {"name": "Latanoprost", "class": "ophthalmic_prostaglandin", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Letrozole", "class": "aromatase_inhibitor", "high_daily_mg": 2.5, "max_daily_mg": 2.5},
    {"name": "Leuprolide", "class": "gnrh_agonist", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Levetiracetam", "class": "antiepileptic", "high_daily_mg": 3000, "max_daily_mg": 3000},
    {"name": "Levocetirizine", "class": "antihistamine", "high_daily_mg": 5, "max_daily_mg": 5},
    {"name": "Levofloxacin", "class": "fluoroquinolone_antibiotic", "high_daily_mg": 750, "max_daily_mg": 750},
    {"name": "Liothyronine", "class": "thyroid_hormone", "high_daily_mg": 0.075, "max_daily_mg": 0.1},
    {"name": "Linezolid", "class": "oxazolidinone_antibiotic", "high_daily_mg": 1200, "max_daily_mg": 1200},
    {"name": "Linagliptin", "class": "dpp4_inhibitor", "high_daily_mg": 5, "max_daily_mg": 5},
    {"name": "Liraglutide", "class": "glp1_receptor_agonist", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Lithium", "class": "mood_stabilizer", "high_daily_mg": 1200, "max_daily_mg": 2400},
    {"name": "Loperamide", "class": "antidiarrheal", "high_daily_mg": 8, "max_daily_mg": 16},
    {"name": "Loratadine", "class": "antihistamine", "high_daily_mg": 10, "max_daily_mg": 10},
    {"name": "Lorazepam", "class": "benzodiazepine", "high_daily_mg": 6, "max_daily_mg": 10},
    {"name": "Losartan", "class": "angiotensin_receptor_blocker", "high_daily_mg": 100, "max_daily_mg": 100},
    {"name": "Melatonin", "class": "sleep_aid", "high_daily_mg": 10, "max_daily_mg": 20},
    {"name": "Meloxicam", "class": "nsaid", "high_daily_mg": 15, "max_daily_mg": 15},
    {"name": "Memantine", "class": "nmda_receptor_antagonist", "high_daily_mg": 20, "max_daily_mg": 28},
    {"name": "Meropenem", "class": "carbapenem_antibiotic", "high_daily_mg": 3000, "max_daily_mg": 6000},
    {"name": "Mesalamine", "class": "aminosalicylate", "high_daily_mg": 2400, "max_daily_mg": 4800},
    {"name": "Methimazole", "class": "antithyroid", "high_daily_mg": 40, "max_daily_mg": 60},
    {"name": "Methocarbamol", "class": "muscle_relaxant", "high_daily_mg": 6000, "max_daily_mg": 8000},
    {"name": "Methotrexate", "class": "antimetabolite", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Methylprednisolone", "class": "corticosteroid", "high_daily_mg": 32, "max_daily_mg": 100},
    {"name": "Metoclopramide", "class": "prokinetic", "high_daily_mg": 40, "max_daily_mg": 40},
    {"name": "Metoprolol", "class": "beta_blocker", "high_daily_mg": 200, "max_daily_mg": 400},
    {"name": "Metronidazole", "class": "nitroimidazole_antibiotic", "high_daily_mg": 1500, "max_daily_mg": 4000},
    {"name": "Minocycline", "class": "tetracycline_antibiotic", "high_daily_mg": 200, "max_daily_mg": 400},
    {"name": "Mirabegron", "class": "beta3_agonist", "high_daily_mg": 50, "max_daily_mg": 50},
    {"name": "Mirtazapine", "class": "antidepressant", "high_daily_mg": 45, "max_daily_mg": 45},
    {"name": "Misoprostol", "class": "prostaglandin_analog", "high_daily_mg": 0.8, "max_daily_mg": 0.8},
    {"name": "Mometasone Nasal", "class": "nasal_corticosteroid", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Montelukast", "class": "leukotriene_receptor_antagonist", "high_daily_mg": 10, "max_daily_mg": 10},
    {"name": "Morphine", "class": "opioid_analgesic", "high_daily_mg": 120, "max_daily_mg": 300},
    {"name": "Moxifloxacin", "class": "fluoroquinolone_antibiotic", "high_daily_mg": 400, "max_daily_mg": 400},
    {"name": "Mupirocin", "class": "topical_antibiotic", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Mycophenolate", "class": "immunosuppressant", "high_daily_mg": 2000, "max_daily_mg": 3000},
    {"name": "Naloxone", "class": "opioid_antagonist", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Naltrexone", "class": "opioid_antagonist", "high_daily_mg": 50, "max_daily_mg": 100},
    {"name": "Naproxen", "class": "nsaid", "high_daily_mg": 1000, "max_daily_mg": 1500},
    {"name": "Nebivolol", "class": "beta_blocker", "high_daily_mg": 20, "max_daily_mg": 40},
    {"name": "Nicotine Patch", "class": "smoking_cessation_agent", "high_daily_mg": 21, "max_daily_mg": 42},
    {"name": "Nifedipine", "class": "calcium_channel_blocker", "high_daily_mg": 90, "max_daily_mg": 120},
    {"name": "Nilotinib", "class": "tyrosine_kinase_inhibitor", "high_daily_mg": 600, "max_daily_mg": 800},
    {"name": "Nitrofurantoin", "class": "nitrofuran_antibiotic", "high_daily_mg": 200, "max_daily_mg": 400},
    {"name": "Nitroglycerin", "class": "nitrate", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Nivolumab", "class": "immune_checkpoint_inhibitor", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Nystatin", "class": "antifungal", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Olanzapine", "class": "atypical_antipsychotic", "high_daily_mg": 20, "max_daily_mg": 20},
    {"name": "Olmesartan", "class": "angiotensin_receptor_blocker", "high_daily_mg": 40, "max_daily_mg": 40},
    {"name": "Ondansetron", "class": "antiemetic", "high_daily_mg": 24, "max_daily_mg": 32},
    {"name": "Oseltamivir", "class": "antiviral", "high_daily_mg": 150, "max_daily_mg": 150},
    {"name": "Osimertinib", "class": "tyrosine_kinase_inhibitor", "high_daily_mg": 80, "max_daily_mg": 80},
    {"name": "Oxcarbazepine", "class": "antiepileptic", "high_daily_mg": 1200, "max_daily_mg": 2400},
    {"name": "Oxybutynin", "class": "anticholinergic_urologic", "high_daily_mg": 15, "max_daily_mg": 30},
    {"name": "Oxycodone", "class": "opioid_analgesic", "high_daily_mg": 80, "max_daily_mg": 160},
    {"name": "Paclitaxel", "class": "taxane_chemotherapy", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Pancrelipase", "class": "pancreatic_enzyme", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Paroxetine", "class": "ssri", "high_daily_mg": 40, "max_daily_mg": 60},
    {"name": "Pazopanib", "class": "tyrosine_kinase_inhibitor", "high_daily_mg": 800, "max_daily_mg": 800},
    {"name": "Pembrolizumab", "class": "immune_checkpoint_inhibitor", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Penicillin V", "class": "penicillin_antibiotic", "high_daily_mg": 2000, "max_daily_mg": 4000},
    {"name": "Perindopril", "class": "ace_inhibitor", "high_daily_mg": 8, "max_daily_mg": 16},
    {"name": "Permethrin", "class": "topical_antiparasitic", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Phenytoin", "class": "antiepileptic", "high_daily_mg": 300, "max_daily_mg": 600},
    {"name": "Pioglitazone", "class": "thiazolidinedione", "high_daily_mg": 45, "max_daily_mg": 45},
    {"name": "Piperacillin Tazobactam", "class": "penicillin_antibiotic", "high_daily_mg": 18000, "max_daily_mg": 24000},
    {"name": "Polyethylene Glycol", "class": "osmotic_laxative", "high_daily_mg": 34000, "max_daily_mg": 68000},
    {"name": "Potassium Chloride", "class": "electrolyte_supplement", "high_daily_mg": 3000, "max_daily_mg": 6000},
    {"name": "Pramipexole", "class": "dopamine_agonist", "high_daily_mg": 3, "max_daily_mg": 4.5},
    {"name": "Pravastatin", "class": "statin", "high_daily_mg": 40, "max_daily_mg": 80},
    {"name": "Pregabalin", "class": "gabapentinoid", "high_daily_mg": 300, "max_daily_mg": 600},
    {"name": "Propylthiouracil", "class": "antithyroid", "high_daily_mg": 300, "max_daily_mg": 900},
    {"name": "Propranolol", "class": "beta_blocker", "high_daily_mg": 160, "max_daily_mg": 640},
    {"name": "Quetiapine", "class": "atypical_antipsychotic", "high_daily_mg": 600, "max_daily_mg": 800},
    {"name": "Rabeprazole", "class": "ppi", "high_daily_mg": 20, "max_daily_mg": 60},
    {"name": "Ramipril", "class": "ace_inhibitor", "high_daily_mg": 10, "max_daily_mg": 20},
    {"name": "Repaglinide", "class": "meglitinide", "high_daily_mg": 12, "max_daily_mg": 16},
    {"name": "Rifampin", "class": "rifamycin_antibiotic", "high_daily_mg": 600, "max_daily_mg": 1200},
    {"name": "Risedronate", "class": "bisphosphonate", "high_daily_mg": 35, "max_daily_mg": 35},
    {"name": "Risperidone", "class": "atypical_antipsychotic", "high_daily_mg": 6, "max_daily_mg": 16},
    {"name": "Rituximab", "class": "monoclonal_antibody_oncology", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Rivaroxaban", "class": "direct_oral_anticoagulant", "high_daily_mg": 20, "max_daily_mg": 30},
    {"name": "Ropinirole", "class": "dopamine_agonist", "high_daily_mg": 8, "max_daily_mg": 24},
    {"name": "Rosuvastatin", "class": "statin", "high_daily_mg": 20, "max_daily_mg": 40},
    {"name": "Salmeterol", "class": "long_acting_beta_agonist", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Saxagliptin", "class": "dpp4_inhibitor", "high_daily_mg": 5, "max_daily_mg": 5},
    {"name": "Secukinumab", "class": "biologic_dmard", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Semaglutide", "class": "glp1_receptor_agonist", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Senna", "class": "stimulant_laxative", "high_daily_mg": 34.4, "max_daily_mg": 70},
    {"name": "Sevelamer", "class": "phosphate_binder", "high_daily_mg": 7200, "max_daily_mg": 14400},
    {"name": "Sildenafil", "class": "pde5_inhibitor", "high_daily_mg": 100, "max_daily_mg": 100},
    {"name": "Simvastatin", "class": "statin", "high_daily_mg": 40, "max_daily_mg": 80},
    {"name": "Sitagliptin", "class": "dpp4_inhibitor", "high_daily_mg": 100, "max_daily_mg": 100},
    {"name": "Sodium Bicarbonate", "class": "alkalinizing_agent", "high_daily_mg": 4000, "max_daily_mg": 10000},
    {"name": "Sofosbuvir", "class": "antiviral", "high_daily_mg": 400, "max_daily_mg": 400},
    {"name": "Solifenacin", "class": "anticholinergic_urologic", "high_daily_mg": 10, "max_daily_mg": 10},
    {"name": "Sorafenib", "class": "tyrosine_kinase_inhibitor", "high_daily_mg": 800, "max_daily_mg": 800},
    {"name": "Sotalol", "class": "antiarrhythmic", "high_daily_mg": 320, "max_daily_mg": 640},
    {"name": "Sucralfate", "class": "gi_mucosal_protectant", "high_daily_mg": 4000, "max_daily_mg": 8000},
    {"name": "Sulfasalazine", "class": "aminosalicylate", "high_daily_mg": 3000, "max_daily_mg": 4000},
    {"name": "Sunitinib", "class": "tyrosine_kinase_inhibitor", "high_daily_mg": 50, "max_daily_mg": 50},
    {"name": "Tacrolimus", "class": "calcineurin_inhibitor", "high_daily_mg": 10, "max_daily_mg": 20},
    {"name": "Tadalafil", "class": "pde5_inhibitor", "high_daily_mg": 20, "max_daily_mg": 40},
    {"name": "Tamsulosin", "class": "alpha1_blocker", "high_daily_mg": 0.4, "max_daily_mg": 0.8},
    {"name": "Telmisartan", "class": "angiotensin_receptor_blocker", "high_daily_mg": 80, "max_daily_mg": 80},
    {"name": "Tenofovir", "class": "antiviral", "high_daily_mg": 300, "max_daily_mg": 300},
    {"name": "Terbinafine", "class": "antifungal", "high_daily_mg": 250, "max_daily_mg": 250},
    {"name": "Tetracycline", "class": "tetracycline_antibiotic", "high_daily_mg": 2000, "max_daily_mg": 2000},
    {"name": "Theophylline", "class": "methylxanthine", "high_daily_mg": 600, "max_daily_mg": 900},
    {"name": "Timolol Eye Drops", "class": "ophthalmic_beta_blocker", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Tiotropium", "class": "long_acting_anticholinergic", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Tizanidine", "class": "muscle_relaxant", "high_daily_mg": 24, "max_daily_mg": 36},
    {"name": "Tobramycin", "class": "aminoglycoside_antibiotic", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Tofacitinib", "class": "jak_inhibitor", "high_daily_mg": 10, "max_daily_mg": 20},
    {"name": "Topiramate", "class": "antiepileptic", "high_daily_mg": 200, "max_daily_mg": 400},
    {"name": "Torsemide", "class": "loop_diuretic", "high_daily_mg": 100, "max_daily_mg": 200},
    {"name": "Tramadol", "class": "opioid_analgesic", "high_daily_mg": 300, "max_daily_mg": 400},
    {"name": "Tranexamic Acid", "class": "antifibrinolytic", "high_daily_mg": 3000, "max_daily_mg": 4000},
    {"name": "Trastuzumab", "class": "monoclonal_antibody_oncology", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Trazodone", "class": "antidepressant", "high_daily_mg": 200, "max_daily_mg": 400},
    {"name": "Tretinoin", "class": "topical_retinoid", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Trimethoprim Sulfamethoxazole", "class": "sulfonamide_antibiotic", "high_daily_mg": 1600, "max_daily_mg": 1920},
    {"name": "Valacyclovir", "class": "antiviral", "high_daily_mg": 3000, "max_daily_mg": 4000},
    {"name": "Valproate", "class": "antiepileptic", "high_daily_mg": 2000, "max_daily_mg": 4000},
    {"name": "Valsartan", "class": "angiotensin_receptor_blocker", "high_daily_mg": 320, "max_daily_mg": 320},
    {"name": "Vancomycin", "class": "glycopeptide_antibiotic", "high_daily_mg": 2000, "max_daily_mg": 4000},
    {"name": "Varenicline", "class": "smoking_cessation_agent", "high_daily_mg": 2, "max_daily_mg": 2},
    {"name": "Venlafaxine", "class": "snri", "high_daily_mg": 225, "max_daily_mg": 375},
    {"name": "Verapamil", "class": "calcium_channel_blocker", "high_daily_mg": 360, "max_daily_mg": 480},
    {"name": "Vincristine", "class": "vinca_alkaloid", "high_daily_mg": None, "max_daily_mg": None},
    {"name": "Vitamin D3", "class": "vitamin", "high_daily_mg": 0.1, "max_daily_mg": 0.25},
    {"name": "Voriconazole", "class": "azole_antifungal", "high_daily_mg": 400, "max_daily_mg": 800},
    {"name": "Zolpidem", "class": "sedative_hypnotic", "high_daily_mg": 10, "max_daily_mg": 10},
]
